--TABLA CLIENTE:
-------------------------------------------------------------------

--CONTEO DE COLUMNAS TABLA CLIENTE:
SELECT  COUNT("CUENTA_CODIGO"),
	COUNT("PLAN_COMERCIAL_DK"),
	COUNT("CONSULTOR_DK"),
	COUNT("ORGANIZACION_ID"),
	COUNT("STAFF_ID"),
	COUNT("SIMCARD"),
	COUNT("MSISDN"),
	COUNT("CICLO_FACTURACION"),
	COUNT("SERVICIO"),
	COUNT("ESTADO"),
	COUNT("SUBSCRIBER_ID"),
	COUNT("ORDEN_CODIGO"),
	COUNT("MOVIMIENTO_NOMBRE"),
	COUNT("MOVIMIENTO_TIPO_NOMBRE"),
	COUNT("OPERADOR_PORTA_ORIGEN"),
	COUNT("OPERADOR_PORTA_DESTINO"),
	COUNT("COMISIONABLE"),
	COUNT("FECHA_ALTA"),
	COUNT("REVENUE"),
	COUNT("FECHA_CARGA_DWH")
FROM CLIENTE;


--CONTEO POR CATEGORÍA DE OPERADOR_PORTA_ORIGEN
SELECT  OPERADOR_PORTA_ORIGEN,COUNT("CUENTA_CODIGO")
FROM CLIENTE
GROUP BY OPERADOR_PORTA_ORIGEN;


--MINIMO, MAXIMO Y PROMEDIO DE LA UNICA COLUMNA REVENUE:
SELECT MIN(REVENUE),MAX(REVENUE),AVG(REVENUE)
FROM CLIENTE;





--TABLA FACTURACIÓN:
-------------------------------------------------------------------

--CONTEO DE COLUMNAS TABLA FACTURACION:
SELECT  COUNT("ID"),
	COUNT("FACTURA_CODIGO"),
	COUNT("FACTURA_FECHA"),
	COUNT("FACTURA_TIPO"),
	COUNT("SUBSCRIBER_ID"),
	COUNT("CUENTA_CODIGO"),	
	COUNT("FACTURA_MONTO"),
	COUNT("FACTURA_FECHA_VENCIMIENTO"),
	COUNT("CONSULTOR_CODIGO")
FROM FACTURACION;


--MINIMO, MAXIMO Y PROMEDIO DE LA UNICA COLUMNA FACTURA_MONTO:
SELECT MIN(FACTURA_MONTO),MAX(FACTURA_MONTO),AVG(FACTURA_MONTO)
FROM FACTURACION;


--¿CUÁLES CUENTAS NO TIENEN CÓDIGO INTERNO DE SERVICIO DEL CLIENTE EN LA FACTURACIÓN?.
SELECT CUENTA_CODIGO, FACTURA_CODIGO, SUBSCRIBER_ID
FROM FACTURACION
WHERE SUBSCRIBER_ID IS NULL;


--¿QUÉ CODIGOS DE FACTURAS TIENEN CUENTAS NULAS Y NO TIENEN CÓDIGO INTERNO DE SERVICIO PERO SI MONTO?.
SELECT ID, CUENTA_CODIGO, FACTURA_CODIGO, SUBSCRIBER_ID,FACTURA_MONTO
FROM FACTURACION
WHERE SUBSCRIBER_ID IS NULL AND CUENTA_CODIGO IS NULL;





--TABLA CONSUMO:
-------------------------------------------------------------------

--CONTEO DE COLUMNAS TABLA CONSUMO:
SELECT  COUNT("ID"),
	COUNT("PERIODO_PROCESO_CODIGO"),
	COUNT("CLIENTE_DK"),
	COUNT("SUBSCRIBER_ID"),
	COUNT("TIPO_EVENTO"),
	COUNT("CICLO_FACTURACION"),
	COUNT("AREA_ID"),
	COUNT("CUENTA_ID"),
	COUNT("OPERADOR_RAN"),
	COUNT("NUMERO_ORIGEN"),
	COUNT("DURACION_SEG"),
	COUNT("LOCALIZACION_USUARIO"),
	COUNT("PLMNID_SGSN"),
	COUNT("PLMNID_GGSN")
FROM CONSUMO;


--MINIMO, MAXIMO Y PROMEDIO DE LA UNICA COLUMNA DURACION_SEG:
SELECT MIN(DURACION_SEG),MAX(DURACION_SEG),AVG(DURACION_SEG)
FROM CONSUMO;


--DESCRIPCION DE LAS COLUMNAS DONDE CLIENTE_DK=-2.
SELECT *
FROM CONSUMO
WHERE CLIENTE_DK=-2;








